### ISSUE TITLE
`ha-google-home` depends on `glocaltokens==0.7.1` which depends on `ghome-foyer-api==1.0.0` which depends on `protobuf>=4.21.12,<5.0.0`, but home assistant is starting to ship with a newer protobuf.

### ISSUE THREAD

**Issue by satmandu** [KapJI/ghome-foyer-api#123] opened 2024-11-04 04:00 UTC
_The issue is that `ha-google-home` depends on `glocaltokens==0.7.1` which depends on `ghome-foyer-api==1.0.0` which, in the end, depends on `protobuf>=4.21.12,<5.0.0`._

_However, HomeAssistant 2024.11 comes with `protobuf==5.28.3`, it was bumped to `5.x` in https://github.com/home-assistant/core/pull/124936 so a new version of `ghome-foyer-api` supporting `protobuf>=5` and a new version of `glocaltokens` is needed._

_For what is worth I've ran the following inside my `homeassistant` container and so far it is working:_

```bash
uv pip install glocaltokens==0.7.1  # This will downgrade protobuff to version 4.25.4
uv pip install protobuf==5.28.3  # Bump again to homeassistant provided version
```

_And after a restart, it seems to be working even with `protobuf>=5`, so maybe is just minor work effort:_
![image](https://github.com/user-attachments/assets/db7a0cad-e089-416f-ba95-45af6fe53710)

_Originally posted by @skgsergio in https://github.com/leikoilja/ha-google-home/issues/918#issuecomment-2453581838_

Any chance we can get a version of `ghome-foyer-api` that works with `protobuf>=5`?

**Comment by KapJI** [comment] 2024-11-04 11:27
Thanks for the report! I'll try to update the dependencies soon.

**Comment by KapJI** [comment] 2024-11-04 11:28
Duplicate of #122

**Closed by KapJI** 2024-11-04 11:28 UTC
